### ISSUE TITLE
Move to surya-soft org

### ISSUE THREAD

**Issue by mayurdhaka-suryasoftware** [gps/newline-at-eof#1]
This repository needs to be moved to the Sura Soft Org.

Also, please clarify in the README whether this action just checks for single EOFs or adds them to files (and removes excessive trailing EOFs) as well?

**Comment by gps** [comment]
> This repository needs to be moved to the Sura Soft Org.

Will do this wholesale (there are other such actions) at some point.

> Also, please clarify in the README whether this action just checks for single EOFs or adds them to files (and removes excessive trailing EOFs) as well?

This is a placeholder repo. It doesn't do anything yet. Scope of work is defined here: https://app.clubhouse.io/surya-leo/story/1768/
